"""initial_schema

Revision ID: 96fb97a39f8d
Revises: 
Create Date: 2026-09-19 12:21:08.871961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
import app.db.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96fb97a39f8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_startup_id'), ['startup_id'], unique=False)

    op.create_table('users',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('startups',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_idea', sa.Text(), nullable=False),
    sa.Column('current_version_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['profile_versions.id'], name='fk_startup_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_index('ix_startups_user_created', ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_startups_user_id'), ['user_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_mode', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('idea', 'value_proposition', 'market', 'business_model')", name='ck_analyses_kind'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index('ix_analyses_startup_kind_created', ['startup_id', 'kind', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('clarification_turns',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('target_field', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('profile_version_before', sa.Integer(), nullable=False),
    sa.Column('profile_version_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'seq', name='uq_clarification_turns_startup_seq')
    )
    with op.batch_alter_table('clarification_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_turns_startup_id'), ['startup_id'], unique=False)

    op.create_table('competitors',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('differentiation', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_startup_id'), ['startup_id'], unique=False)

    op.create_table('pitch_versions',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('slides', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('parent_pitch_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('ai_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_pitch_id'], ['pitch_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'version', name='uq_pitch_versions_startup_version')
    )
    with op.batch_alter_table('pitch_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pitch_versions_startup_id'), ['startup_id'], unique=False)

    op.create_table('profile_versions',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('change_reason', sa.String(length=50), nullable=False),
    sa.Column('completeness_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'version', name='uq_profile_versions_startup_version')
    )
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_versions_startup_id'), ['startup_id'], unique=False)

    op.create_table('evidence_sources',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('analysis_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.CheckConstraint("kind IN ('search_result', 'founder_provided')", name='ck_evidence_sources_kind'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_sources_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_sources_startup_id'), ['startup_id'], unique=False)

    op.create_table('investor_sessions',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('pitch_version_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name='ck_investor_sessions_status'),
    sa.ForeignKeyConstraint(['pitch_version_id'], ['pitch_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_sessions_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index('ix_investor_sessions_startup_started', ['startup_id', sa.literal_column('started_at DESC')], unique=False)

    op.create_table('pitch_critiques',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('pitch_version_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pitch_version_id'], ['pitch_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitch_critiques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pitch_critiques_pitch_version_id'), ['pitch_version_id'], unique=False)

    op.create_table('investor_turns',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("intent IN ('opening', 'follow_up', 'new_topic')", name='ck_investor_turns_intent'),
    sa.ForeignKeyConstraint(['session_id'], ['investor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_investor_turns_session_seq')
    )
    with op.batch_alter_table('investor_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_turns_session_id'), ['session_id'], unique=False)

    op.create_table('readiness_reports',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('narrative', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['investor_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readiness_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_reports_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_readiness_reports_startup_created', ['startup_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_reports_startup_id'), ['startup_id'], unique=False)

    op.create_table('feedback_items',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('startup_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('report_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('suggested_patch', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'accepted', 'dismissed', 'done')", name='ck_feedback_items_status'),
    sa.ForeignKeyConstraint(['report_id'], ['readiness_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_items_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_items_startup_id'), ['startup_id'], unique=False)
        batch_op.create_index('ix_feedback_items_startup_status', ['startup_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_items_startup_status')
        batch_op.drop_index(batch_op.f('ix_feedback_items_startup_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_items_report_id'))

    op.drop_table('feedback_items')
    with op.batch_alter_table('readiness_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_reports_startup_id'))
        batch_op.drop_index('ix_readiness_reports_startup_created')
        batch_op.drop_index(batch_op.f('ix_readiness_reports_session_id'))

    op.drop_table('readiness_reports')
    with op.batch_alter_table('investor_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_turns_session_id'))

    op.drop_table('investor_turns')
    with op.batch_alter_table('pitch_critiques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pitch_critiques_pitch_version_id'))

    op.drop_table('pitch_critiques')
    with op.batch_alter_table('investor_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_investor_sessions_startup_started')
        batch_op.drop_index(batch_op.f('ix_investor_sessions_startup_id'))

    op.drop_table('investor_sessions')
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_sources_startup_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_sources_analysis_id'))

    op.drop_table('evidence_sources')
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_versions_startup_id'))

    op.drop_table('profile_versions')
    with op.batch_alter_table('pitch_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pitch_versions_startup_id'))

    op.drop_table('pitch_versions')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_startup_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('clarification_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_turns_startup_id'))

    op.drop_table('clarification_turns')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_analyses_startup_kind_created')
        batch_op.drop_index(batch_op.f('ix_analyses_startup_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startups_user_id'))
        batch_op.drop_index('ix_startups_user_created')

    op.drop_table('startups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_startup_id'))

    op.drop_table('llm_calls')
    # ### end Alembic commands ###
